macro(OSDISTRO OSName)
if(LINUX)
set(${OSName} "LINUX")
message("====" ${${OSName}})
elseif(WIN32)
set(${OSName} "WIN")
message("====" ${${OSName}} )
elseif(MACOSX_BUNDLE)
set(${OSName} "MAC")
message("====" ${${OSName}} )
endif()
endmacro()